version: "3"
services:
  # Create frontend container
  frontend: # Name of our service
    build: ./front-end # path to dockerfile
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    links:
      - backend
    networks:
      - webappnetwork

  # Create backend container
  backend:
    # Create backend container
    build: ./back-end
    ports:
      - "3001:3001"
    container_name: backend-docker
    restart: always
    # links:
    #   - db
    networks:
      - webappnetwork

  # We dont need a seperate container for database since we are using Atlas
  # Create database container
  # db:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   container_name: database-docker
  #   restart: always
  #   networks:
  #     - webappnetwork

networks:
  webappnetwork:
    driver: bridge
